project_id = "ffsnesetkdgapwrwmscf"

[functions.send-invitation]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.notify-maintenance]
verify_jwt = false

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.rent-reminder]
verify_jwt = false
